// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LSP_BattleActorPositions","status":true,"description":"Places side-view party battlers on the right side of the battle field.","parameters":{}}
];
